version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /home/james/server/configs/plex:/config
      - /home/james/server/media/tv:/tv
      - /home/james/server/media/movies:/movies
    restart: unless-stopped
