version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/james/server/configs/sonarr:/config
      - /home/james/server/media:/media
      - /home/james/server/data/downloads:/data/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
networks: {}
