services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - ../../media:/media
      - ../../data/downloads:/data/downloads
    ports:
      - 8080:8080
    restart: unless-stopped
networks: {}
